name: scicanvas
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  # Core deep learning frameworks
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  
  # Scientific computing
  - numpy=2.0.0
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - numba=0.61.0
  
  # Single-cell analysis
  - scanpy=1.11.1
  - anndata=0.11.4
  - umap-learn=0.5.7
  - pynndescent=0.5.13
  
  # Data processing
  - h5py=3.13.0
  - tqdm=4.67.1
  
  # Visualization
  - matplotlib-base=3.10.0
  - seaborn=0.13.2
  - pillow=11.0.0
  
  # Development tools
  - jupyter=1.1.1
  - jupyterlab=4.3.4
  - notebook=7.3.2
  
  # Statistical analysis
  - statsmodels=0.14.4
  - networkx=3.2.1
  
  # Utilities
  - pyyaml=6.0.2
  - requests=2.32.3
  - packaging=24.2
  
  # Pip dependencies
  - pip
  - pip:
    - scipy==1.14.1
    - tensorboard==2.19.0
    - wandb==0.19.11
    - opencv-python==4.10.0.84 